server.port=4000

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/board_jihoon?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=jk97121024^^
=======
spring.datasource.password=root
>>>>>>> ca9f804b5d7ab7645abdce17591d2a28a2518c4f

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=110MB

<<<<<<< HEAD
file.path=C:/uploads
=======
# /* 수정필요 */
file.path=C:/Users/win11/Desktop/OpenSourceProject/board/images
>>>>>>> ca9f804b5d7ab7645abdce17591d2a28a2518c4f
file.url=http://localhost:4000/file/
file.upload-dir=C:/uploads



secret-key=S3cr3tK3y
